# Generated by Django 6.0.4 on 2026-08-04 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organize', '0026_merge_20260721_1415'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — not yet set up'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished')], default='DRAFT', max_length=16)),
                ('seed', models.BigIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tick_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_runs', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_runs', to='organize.game')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_runs', to='organize.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=32)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organize.userprofile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organize.team')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='simulator.simulationrun')),
            ],
            options={
                'ordering': ['run_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(default=0)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('SPAWN', 'Spawn'), ('MOVE', 'Move'), ('PROXIMITY', 'Proximity / dementors tick'), ('CAPTURE', 'Tower capture'), ('TRANSITION', 'Session lifecycle transition'), ('TICK', 'Tick boundary')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulator.simulationrun')),
            ],
            options={
                'ordering': ['run_id', 'tick', 'id'],
                'indexes': [models.Index(fields=['run', 'tick'], name='simulator_s_run_id_2e8a3c_idx')],
            },
        ),
    ]
