/*
 * Generated by a one-off script from the source SVGs in this directory —
 * do not hand-edit. Re-run the generator after changing an .svg file.
 * See docs/design-system.md §4 for the icon set contract.
 */

export const UI_ICON_NAMES = [
  'arrow-right',
  'bell',
  'book',
  'camera',
  'castle',
  'chevron-left',
  'clock',
  'compass',
  'id-card',
  'key',
  'lightbulb',
  'map',
  'sparkle',
  'star',
  'target',
  'users',
] as const;

export type UiIconName = (typeof UI_ICON_NAMES)[number];

export const ICON_PATHS: Record<UiIconName, string> = {
  'arrow-right': `<g><path d="M5 12H19" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M13 6L19 12L13 18" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  bell: `<g><path d="M6.5 9.5C6.5 8.04131 7.07946 6.64236 8.11091 5.61091C9.14236 4.57946 10.5413 4 12 4C13.4587 4 14.8576 4.57946 15.8891 5.61091C16.9205 6.64236 17.5 8.04131 17.5 9.5C17.5 13.5 19.3 15 19.3 15H4.7C4.7 15 6.5 13.5 6.5 9.5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M10 19C10 19.5304 10.2107 20.0391 10.5858 20.4142C10.9609 20.7893 11.4696 21 12 21C12.5304 21 13.0391 20.7893 13.4142 20.4142C13.7893 20.0391 14 19.5304 14 19" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  book: `<g><path d="M4 5.5C4 4.96957 4.21071 4.46086 4.58579 4.08579C4.96086 3.71071 5.46957 3.5 6 3.5H12V18.5H6C5.46957 18.5 4.96086 18.7107 4.58579 19.0858C4.21071 19.4609 4 19.9696 4 20.5V5.5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M20 5.5C20 4.96957 19.7893 4.46086 19.4142 4.08579C19.0391 3.71071 18.5304 3.5 18 3.5H12V18.5H18C18.5304 18.5 19.0391 18.7107 19.4142 19.0858C19.7893 19.4609 20 19.9696 20 20.5V5.5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  camera: `<g><path d="M4 8.5H7.5L9 6.5H15L16.5 8.5H20C20.2652 8.5 20.5196 8.60536 20.7071 8.79289C20.8946 8.98043 21 9.23478 21 9.5V19C21 19.2652 20.8946 19.5196 20.7071 19.7071C20.5196 19.8946 20.2652 20 20 20H4C3.73478 20 3.48043 19.8946 3.29289 19.7071C3.10536 19.5196 3 19.2652 3 19V9.5C3 9.23478 3.10536 8.98043 3.29289 8.79289C3.48043 8.60536 3.73478 8.5 4 8.5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 16.7C13.7673 16.7 15.2 15.2673 15.2 13.5C15.2 11.7327 13.7673 10.3 12 10.3C10.2327 10.3 8.8 11.7327 8.8 13.5C8.8 15.2673 10.2327 16.7 12 16.7Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  castle: `<g><path d="M4 21V9H6V6H8V9H10V6H12V9H14V6H16V9H18V21H4Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M9 21V17H15V21" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  'chevron-left': `<g><path d="M15 18L9 12L15 6" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  clock: `<g><path d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 7.5V12L15 13.8" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  compass: `<g><path d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M15.5 8.5L13.3 13.3L8.5 15.5L10.7 10.7L15.5 8.5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  'id-card': `<g><path d="M18.5 5H5.5C4.39543 5 3.5 5.89543 3.5 7V17C3.5 18.1046 4.39543 19 5.5 19H18.5C19.6046 19 20.5 18.1046 20.5 17V7C20.5 5.89543 19.6046 5 18.5 5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M9 13.2C10.215 13.2 11.2 12.215 11.2 11C11.2 9.78497 10.215 8.8 9 8.8C7.78497 8.8 6.8 9.78497 6.8 11C6.8 12.215 7.78497 13.2 9 13.2Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M13.5 10H17.5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M13.5 13.5H17.5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M7 16.5H17" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  key: `<g><path d="M8 19C10.2091 19 12 17.2091 12 15C12 12.7909 10.2091 11 8 11C5.79086 11 4 12.7909 4 15C4 17.2091 5.79086 19 8 19Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M10.8 12.2L19 4" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M16.5 4.5L18.5 6.5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M14.5 6.5L16.5 8.5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  lightbulb: `<g><path d="M9.5 17.5H14.5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M10.5 20.5H13.5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 3.5C11.019 3.51946 10.0611 3.80099 9.22555 4.3154C8.39002 4.82981 7.70732 5.55838 7.24823 6.42554C6.78915 7.2927 6.5704 8.26688 6.61467 9.24707C6.65894 10.2273 6.96461 11.1778 7.5 12C8.3 12.9 9 13.8 9.2 15H14.8C15 13.8 15.7 12.9 16.5 12C17.0354 11.1778 17.3411 10.2273 17.3853 9.24707C17.4296 8.26688 17.2109 7.2927 16.7518 6.42554C16.2927 5.55838 15.61 4.82981 14.7744 4.3154C13.9389 3.80099 12.981 3.51946 12 3.5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  map: `<g><path d="M9 4.5L3.5 6.5V19.5L9 17.5L15 19.5L20.5 17.5V4.5L15 6.5L9 4.5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M9 4.5V17.5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M15 6.5V19.5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  sparkle: `<g><path d="M12 3L13.7 8.3L19 10L13.7 11.7L12 17L10.3 11.7L5 10L10.3 8.3L12 3Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  star: `<g><path d="M12 3.5L14.6 8.8L20.5 9.7L16.2 13.8L17.2 19.6L12 16.9L6.8 19.6L7.8 13.8L3.5 9.7L9.4 8.8L12 3.5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  target: `<g><path d="M12 20C16.4183 20 20 16.4183 20 12C20 7.58172 16.4183 4 12 4C7.58172 4 4 7.58172 4 12C4 16.4183 7.58172 20 12 20Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 15.2C13.7673 15.2 15.2 13.7673 15.2 12C15.2 10.2327 13.7673 8.8 12 8.8C10.2327 8.8 8.8 10.2327 8.8 12C8.8 13.7673 10.2327 15.2 12 15.2Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 2V5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 19V22" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M2 12H5" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M19 12H22" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
  users: `<g><path d="M9 11.5C10.6569 11.5 12 10.1569 12 8.5C12 6.84315 10.6569 5.5 9 5.5C7.34315 5.5 6 6.84315 6 8.5C6 10.1569 7.34315 11.5 9 11.5Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M3.5 20C3.5 17 6 15.2 9 15.2C12 15.2 14.5 17 14.5 20" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M17.5 10.9C18.8255 10.9 19.9 9.82548 19.9 8.5C19.9 7.17452 18.8255 6.1 17.5 6.1C16.1745 6.1 15.1 7.17452 15.1 8.5C15.1 9.82548 16.1745 10.9 17.5 10.9Z" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/><path d="M16 15.4C18.6 15.7 20.5 17.3 20.5 20" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></g>`,
};
