# Generated by Django 6.0.4 on 2026-07-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0009_drop_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fail_cooloff_scaling',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='game',
            name='fail_counter_reset',
            field=models.CharField(choices=[('TOWER_SUCCESS_ONLY', 'Reset only on a confirmed submission at the same tower'), ('ANY_SUCCESS_ELSEWHERE', 'Also reset on a confirmed submission at any other tower'), ('ANY_ATTEMPT_ELSEWHERE', 'Also reset on any submission at any other tower')], default='TOWER_SUCCESS_ONLY', max_length=32),
        ),
        migrations.AddField(
            model_name='game',
            name='fail_difficulty_rollback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='fail_point_penalty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='fail_tower_lockout_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='pause_freezes_floating_score',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pause_rejects_submissions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pause_restores_ownerships_on_resume',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='fail_cooloff_scaling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='fail_counter_reset',
            field=models.CharField(blank=True, choices=[('TOWER_SUCCESS_ONLY', 'Reset only on a confirmed submission at the same tower'), ('ANY_SUCCESS_ELSEWHERE', 'Also reset on a confirmed submission at any other tower'), ('ANY_ATTEMPT_ELSEWHERE', 'Also reset on any submission at any other tower')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='fail_difficulty_rollback',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='fail_point_penalty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='fail_tower_lockout_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='pause_freezes_floating_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='pause_rejects_submissions',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='pause_restores_ownerships_on_resume',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
