# Generated by Django 6.0.4 on 2026-07-20 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0010_game_fail_cooloff_scaling_game_fail_counter_reset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('builtin_power', models.CharField(choices=[('NONE', 'No built-in power'), ('INVITER', 'Inviter — may invite players into their team')], default='NONE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organize.game')),
            ],
            options={
                'unique_together': {('game', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organize.teammembership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organize.gamerole')),
            ],
            options={
                'unique_together': {('membership', 'role')},
            },
        ),
    ]
