# Generated by Django 6.0.4 on 2026-07-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0010_game_fail_cooloff_scaling_game_fail_counter_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN_FOR_PARTICIPANTS', 'Open for participants'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished')], default='DRAFT', max_length=32),
        ),
    ]
