# Generated by Django 6.0.4 on 2026-07-20 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_collection'),
        ('organize', '0010_game_fail_cooloff_scaling_game_fail_counter_reset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='organize.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.collection'),
        ),
        migrations.CreateModel(
            name='GameCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREATOR', 'Creator — may edit the game template'), ('RUNNER', 'Runner — may run sessions under the game')], default='RUNNER', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='organize.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
    ]
