# Generated by Django 6.0.4 on 2026-07-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0010_game_fail_cooloff_scaling_game_fail_counter_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_members_per_team',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='max_teams',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='min_members_per_team',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='min_teams',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='max_members_per_team',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='max_teams',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='min_members_per_team',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='min_teams',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
