# Generated by Django 6.0.4 on 2026-07-20 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0010_game_fail_cooloff_scaling_game_fail_counter_reset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allow_player_team_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='team_join_confirmation',
            field=models.CharField(choices=[('AUTO_APPROVE', 'Auto-approve joins'), ('CAPTAIN', 'Captain approves joins'), ('STAFF', 'Staff approve joins')], default='AUTO_APPROVE', max_length=16),
        ),
        migrations.AddField(
            model_name='invite',
            name='kind',
            field=models.CharField(choices=[('QR', 'Untied QR / shareable code'), ('LINK', 'Recipient-bound link')], default='QR', max_length=8),
        ),
        migrations.AddField(
            model_name='session',
            name='allow_player_team_creation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_captained', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='join_code',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_join_confirmation',
            field=models.CharField(blank=True, choices=[('AUTO_APPROVE', 'Auto-approve joins'), ('CAPTAIN', 'Captain approves joins'), ('STAFF', 'Staff approve joins')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('source', models.CharField(choices=[('BROWSE', 'Browsed the team list'), ('QR', 'Scanned an untied QR / join code'), ('LINK', 'Followed a recipient-bound invite link')], default='BROWSE', max_length=8)),
                ('note', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='organize.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='organize.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('team', 'user'), name='unique_pending_join_request')],
            },
        ),
    ]
