# Generated by Django 6.0.4 on 2026-07-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0012_backfill_session_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_active',
        ),
    ]
