# Generated by Django 6.0.4 on 2026-07-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0011_gamerole_teamrole'),
        ('organize', '0013_drop_session_is_active'),
    ]

    operations = [
    ]
