# Generated by Django 6.0.4 on 2026-07-20 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0011_game_team_rules'),
        ('organize', '0014_merge_20260720_2331'),
    ]

    operations = [
    ]
