# Generated by Django 6.0.4 on 2026-07-20 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0012_backfill_invite_kind'),
        ('organize', '0015_merge_0011_game_team_rules_0014_merge_20260720_2331'),
    ]

    operations = [
    ]
