# Generated by Django 6.0.4 on 2026-07-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0011_game_collections_roles_cloning'),
        ('organize', '0016_merge_20260720_2357'),
    ]

    operations = [
    ]
