# Generated by Django 6.0.4 on 2026-07-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0016_merge_20260720_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ble_freshness_window_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='game',
            name='ble_identity_rotation_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='game',
            name='ble_report_interval_seconds',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='ble_rssi_hysteresis_db',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='ble_rssi_near_dbm',
            field=models.SmallIntegerField(default=-75),
        ),
        migrations.AddField(
            model_name='game',
            name='ble_rssi_very_close_dbm',
            field=models.SmallIntegerField(default=-55),
        ),
        migrations.AddField(
            model_name='game',
            name='ble_scan_duty_cycle_percent',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_conversion_threshold',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_drain_per_second',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_drain_range_bucket',
            field=models.CharField(choices=[('VERY_CLOSE', 'Very close'), ('NEAR', 'Near'), ('FAR', 'Far')], default='NEAR', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_empty_outcome',
            field=models.CharField(choices=[('FLIP', 'Flip to dementor on empty'), ('DIE', 'Out of play on empty')], default='FLIP', max_length=8),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_initial_dementors',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_restore_per_second',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_reverse_group_size',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_reverse_hold_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_safety_in_numbers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_starting_energy',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_tick_seconds',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='dementor_wizard_regen_per_second',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='game',
            name='dementors_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='require_ble_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='ble_freshness_window_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ble_identity_rotation_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ble_report_interval_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ble_rssi_hysteresis_db',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ble_rssi_near_dbm',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ble_rssi_very_close_dbm',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ble_scan_duty_cycle_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_conversion_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_drain_per_second',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_drain_range_bucket',
            field=models.CharField(blank=True, choices=[('VERY_CLOSE', 'Very close'), ('NEAR', 'Near'), ('FAR', 'Far')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_empty_outcome',
            field=models.CharField(blank=True, choices=[('FLIP', 'Flip to dementor on empty'), ('DIE', 'Out of play on empty')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_initial_dementors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_restore_per_second',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_reverse_group_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_reverse_hold_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_safety_in_numbers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_starting_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_tick_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementor_wizard_regen_per_second',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='dementors_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='require_ble_capable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
