# Generated by Django 6.0.4 on 2026-07-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0017_merge_20260721_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('DOMINATION', 'Domination — capture towers, hold zones'), ('TRAIL', 'Trail / discovery — clue-driven point-to-point run')], default='DOMINATION', max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='mode',
            field=models.CharField(blank=True, choices=[('DOMINATION', 'Domination — capture towers, hold zones'), ('TRAIL', 'Trail / discovery — clue-driven point-to-point run')], max_length=16, null=True),
        ),
    ]
