# Generated by Django 6.0.4 on 2026-07-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0017_merge_20260721_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score_time_unit',
            field=models.CharField(choices=[('SECOND', 'Seconds'), ('MINUTE', 'Minutes (default, historical behavior)'), ('HOUR', 'Hours')], default='MINUTE', max_length=8),
        ),
        migrations.AddField(
            model_name='game',
            name='zone_conquest_rule',
            field=models.CharField(choices=[('ALL', 'All towers — a team must hold every active member tower'), ('MAJORITY', 'Majority of towers (default, historical behavior)'), ('ANY', 'Any tower — most towers wins, ties broken by most recent capture')], default='MAJORITY', max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='score_time_unit',
            field=models.CharField(blank=True, choices=[('SECOND', 'Seconds'), ('MINUTE', 'Minutes (default, historical behavior)'), ('HOUR', 'Hours')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='zone_conquest_rule',
            field=models.CharField(blank=True, choices=[('ALL', 'All towers — a team must hold every active member tower'), ('MAJORITY', 'Majority of towers (default, historical behavior)'), ('ANY', 'Any tower — most towers wins, ties broken by most recent capture')], max_length=16, null=True),
        ),
    ]
