# Generated by Django 6.0.4 on 2026-07-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0017_merge_20260721_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='location_consent_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='location_ping_interval_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='game',
            name='location_retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='game',
            name='location_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='location_visibility',
            field=models.CharField(choices=[('NONE', 'Stored only — no live positions shown to players'), ('OWN_TEAM', 'Players see their own team'), ('EVERYONE', 'Players see everyone')], default='OWN_TEAM', max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='location_consent_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='location_ping_interval_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='location_retention_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='location_tracking_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='location_visibility',
            field=models.CharField(blank=True, choices=[('NONE', 'Stored only — no live positions shown to players'), ('OWN_TEAM', 'Players see their own team'), ('EVERYONE', 'Players see everyone')], max_length=16, null=True),
        ),
    ]
