# Generated by Django 6.0.4 on 2026-07-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0017_merge_20260721_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tower_lock_finish_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='game',
            name='tower_lock_mode',
            field=models.CharField(choices=[('FREE_FOR_ALL', 'Free for all — last confirmed finish owns the tower'), ('LOCK_ON_INITIATE', 'Lock on initiate — the initiating team gets an exclusive finish window')], default='FREE_FOR_ALL', max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='tower_lock_finish_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tower_lock_mode',
            field=models.CharField(blank=True, choices=[('FREE_FOR_ALL', 'Free for all — last confirmed finish owns the tower'), ('LOCK_ON_INITIATE', 'Lock on initiate — the initiating team gets an exclusive finish window')], max_length=16, null=True),
        ),
    ]
