# Generated by Django 6.0.4 on 2026-07-21 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0017_merge_20260721_0017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='push_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='realtime_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='push_notifications_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='realtime_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('notify_steal', models.BooleanField(default=True)),
                ('notify_conquer', models.BooleanField(default=True)),
                ('notify_bonus', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('WEBPUSH', 'Web Push (VAPID)'), ('FCM', 'Firebase Cloud Messaging')], default='WEBPUSH', max_length=8)),
                ('endpoint', models.TextField(blank=True, default='')),
                ('p256dh', models.CharField(blank=True, default='', max_length=255)),
                ('auth', models.CharField(blank=True, default='', max_length=255)),
                ('fcm_token', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
