# Generated by Django 6.0.4 on 2026-07-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0017_merge_20260721_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nfc_replay_hardening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='nfc_require_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='nfc_secure_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='nfc_replay_hardening',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='nfc_require_app',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='nfc_secure_mode',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
