# Generated by Django 6.0.4 on 2026-07-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0018_location_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='presence_window_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='teammate_visibility_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='teammate_visibility_mode',
            field=models.CharField(choices=[('OWN_TEAM', 'Own team only'), ('EVERYONE', 'Everyone in the session'), ('SELECT_COUNT', 'The nearest N players')], default='OWN_TEAM', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='togetherness_mode',
            field=models.CharField(choices=[('SPLIT_ALLOWED', 'Members may split up'), ('WHOLE_TEAM_TOGETHER', 'Whole team must be together')], default='SPLIT_ALLOWED', max_length=32),
        ),
        migrations.AddField(
            model_name='session',
            name='presence_window_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='teammate_visibility_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='teammate_visibility_mode',
            field=models.CharField(blank=True, choices=[('OWN_TEAM', 'Own team only'), ('EVERYONE', 'Everyone in the session'), ('SELECT_COUNT', 'The nearest N players')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='togetherness_mode',
            field=models.CharField(blank=True, choices=[('SPLIT_ALLOWED', 'Members may split up'), ('WHOLE_TEAM_TOGETHER', 'Whole team must be together')], max_length=32, null=True),
        ),
    ]
