# Generated by Django 6.0.4 on 2026-07-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0018_game_session_conquest_scoring_knobs'),
        ('organize', '0019_presence_config'),
    ]

    operations = [
    ]
