# Generated by Django 6.0.4 on 2026-07-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0020_merge_20260721_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='challenge_visibility_default',
            field=models.CharField(choices=[('HIDDEN_UNTIL_ARRIVAL', 'Hidden until arrival — legible only inside the activation area'), ('VISIBLE_ANYWHERE', 'Visible anywhere — legible from afar (default, historical behavior)')], default='VISIBLE_ANYWHERE', max_length=32),
        ),
        migrations.AddField(
            model_name='game',
            name='fog_reveal_coverage_pct_default',
            field=models.FloatField(default=60),
        ),
        migrations.AddField(
            model_name='game',
            name='reveal_other_teams_ownership',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='tower_discoverability_default',
            field=models.CharField(choices=[('HIDDEN', 'Hidden — pops up when a team walks within proximity'), ('VISIBLE', 'Visible — always on the map (default, historical behavior)'), ('FOG_REVEAL', 'Fog reveal — revealed by entering or covering the zone')], default='VISIBLE', max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='challenge_visibility_default',
            field=models.CharField(blank=True, choices=[('HIDDEN_UNTIL_ARRIVAL', 'Hidden until arrival — legible only inside the activation area'), ('VISIBLE_ANYWHERE', 'Visible anywhere — legible from afar (default, historical behavior)')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='fog_reveal_coverage_pct_default',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='reveal_other_teams_ownership',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tower_discoverability_default',
            field=models.CharField(blank=True, choices=[('HIDDEN', 'Hidden — pops up when a team walks within proximity'), ('VISIBLE', 'Visible — always on the map (default, historical behavior)'), ('FOG_REVEAL', 'Fog reveal — revealed by entering or covering the zone')], max_length=16, null=True),
        ),
    ]
