# Generated by Django 6.0.4 on 2026-07-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0018_realtime_and_push'),
        ('organize', '0020_merge_20260721_0655'),
    ]

    operations = [
    ]
