# Generated by Django 6.0.4 on 2026-07-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0018_nfc_config_knobs'),
        ('organize', '0021_merge_0018_realtime_and_push_0020_merge_20260721_0655'),
    ]

    operations = [
    ]
