# Generated by Django 6.0.4 on 2026-07-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0018_game_mode'),
        ('organize', '0022_merge_20260721_1109'),
    ]

    operations = [
    ]
