# Generated by Django 6.0.4 on 2026-07-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0018_tower_lock_config'),
        ('organize', '0023_merge_0018_game_mode_0022_merge_20260721_1109'),
    ]

    operations = [
    ]
