# Generated by Django 6.0.4 on 2026-07-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0017_dementors_ble_config'),
        ('organize', '0024_merge_20260721_1201'),
    ]

    operations = [
    ]
