# Generated by Django 6.0.4 on 2026-07-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0021_tower_visibility_discovery'),
        ('organize', '0025_merge_20260721_1317'),
    ]

    operations = [
    ]
