"""
Django settings for geogame project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+%qrqv+(+dg#o0myc5-wnj)@!ywf9-agl*r(ug8r!xeeo3!!8v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'cercetador.albascout.ro']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'channels',
    'leaflet',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_gis',
    'colorfield',
    'smart_selects',

    'game',
    'organize',
    'authoring',
    'simulator',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geogame.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geogame.wsgi.application'

# Realtime (realtime-and-notifications): Channels ASGI application. The
# WSGI entrypoint keeps working for deployments that do not enable
# real-time; websockets are only served when the app runs under ASGI.
ASGI_APPLICATION = 'geogame.asgi.application'

# Channel layer: Redis-backed only when REDIS_URL is set (production,
# cross-process fan-out); otherwise the in-memory layer, which is
# correct for tests and single-process development and needs no extra
# services.
_REDIS_URL = os.environ.get('REDIS_URL')
if _REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_REDIS_URL]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Cache: Redis when available, local memory otherwise. The only thing
# that currently depends on it is the share-link rate limit, which is
# per-process on LocMem — acceptable for development, and the reason
# production sets REDIS_URL.
if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'geogame-default',
        },
    }

# Coalesce `scoreboard.updated` broadcasts to at most one per this many
# seconds per Session (0 disables throttling — used by tests).
REALTIME_SCOREBOARD_THROTTLE_SECONDS = float(
    os.environ.get('REALTIME_SCOREBOARD_THROTTLE_SECONDS', '2.0'),
)

# Web Push (VAPID) / FCM credentials. Without keys the push sender
# degrades to a logging stub — nothing is actually delivered, and no
# external service is contacted (see organize/push.py).
WEBPUSH_VAPID_PUBLIC_KEY = os.environ.get('WEBPUSH_VAPID_PUBLIC_KEY', '')
WEBPUSH_VAPID_PRIVATE_KEY = os.environ.get('WEBPUSH_VAPID_PRIVATE_KEY', '')
WEBPUSH_VAPID_CLAIMS_EMAIL = os.environ.get(
    'WEBPUSH_VAPID_CLAIMS_EMAIL', 'noreply@cercetador.albascout.ro',
)
FCM_SERVER_KEY = os.environ.get('FCM_SERVER_KEY', '')


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DB_NAME', 'geogame'),
        'USER': os.environ.get('DB_USER', 'yeti_db'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'sql123.'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'TEST': {
            'NAME': os.environ.get('DB_TEST_NAME', 'geogame_test'),
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permiss1ions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    # Only the unauthenticated share-link endpoints throttle today; the
    # scope is keyed on the link token rather than the client address so
    # one busy display cannot spend another display's budget.
    'DEFAULT_THROTTLE_RATES': {
        'overview_link': os.environ.get('OVERVIEW_LINK_THROTTLE_RATE', '120/min'),
    },
}

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@cercetador.albascout.ro')

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (46.068374, 23.571797),
    'DEFAULT_ZOOM': 15,
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
BASE_URL = os.environ.get("BASE_URL", "http://127.0.0.1:8200")

MEDIA_ROOT = BASE_DIR / 'media'

# Reference media on towers and zones (tower-zone-media). Caps are per
# kind and are enforced server-side; the field client applies the same
# numbers up front so a curator learns the limit before recording rather
# than after walking away. Raise them per install if the pipe allows —
# `game.media.limits_for` merges whatever is named here over the
# documented defaults in `game.media.DEFAULT_LIMITS`, so overriding one
# number does not mean restating the other five.
MEDIA_ASSET_LIMITS = {
    # A photo is downscaled on the device before it is sent, so this cap
    # catches a client that failed to, not a curator being careless.
    'IMAGE': {
        'max_bytes': int(os.environ.get('MEDIA_IMAGE_MAX_BYTES', 12 * 1024 * 1024)),
    },
    # Three minutes is a long spoken note; past that it is a recording
    # someone forgot to stop.
    'AUDIO': {
        'max_bytes': int(os.environ.get('MEDIA_AUDIO_MAX_BYTES', 12 * 1024 * 1024)),
        'max_seconds': int(os.environ.get('MEDIA_AUDIO_MAX_SECONDS', 180)),
    },
    # A clip shows an approach or a route. Thirty seconds is enough for
    # either, and short enough that a curator on mobile data can send one.
    'VIDEO': {
        'max_bytes': int(os.environ.get('MEDIA_VIDEO_MAX_BYTES', 48 * 1024 * 1024)),
        'max_seconds': int(os.environ.get('MEDIA_VIDEO_MAX_SECONDS', 30)),
    },
}

# A video clip arrives as one multipart part; Django's default in-memory
# ceiling would otherwise refuse it before any of our own limits get a
# say, and the error that produces names nothing useful.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', 64 * 1024 * 1024),
)

# --- challenge-media -------------------------------------------------------
# Per-kind upload limits for media that is part of a Challenge. The MIME
# allowlists are deliberately narrow: every listed type is one the
# duration probe can actually read, so the allowlist and the probe agree
# and no file is ever stored with an unknown duration. WebM is absent for
# that reason — see docs/deployment.md.
CHALLENGE_MEDIA_MIME_TYPES = {
    'IMAGE': ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
    'AUDIO': ['audio/mpeg', 'audio/mp4', 'audio/ogg', 'audio/flac', 'audio/wav', 'audio/x-wav'],
    'VIDEO': ['video/mp4', 'video/quicktime'],
}
CHALLENGE_MEDIA_MAX_BYTES = {
    'IMAGE': 10 * 1024 * 1024,
    'AUDIO': 25 * 1024 * 1024,
    'VIDEO': 100 * 1024 * 1024,
}
# Only the timed kinds are bounded by duration.
CHALLENGE_MEDIA_MAX_SECONDS = {
    'AUDIO': 300,
    'VIDEO': 180,
}

try:
    from .local_settings import *
except ImportError:
    pass
