"""
Django settings for geogame project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+%qrqv+(+dg#o0myc5-wnj)@!ywf9-agl*r(ug8r!xeeo3!!8v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'cercetador.albascout.ro']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'corsheaders',
    'channels',
    'leaflet',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_gis',
    'colorfield',
    'smart_selects',

    'game',
    'organize',
    'authoring',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geogame.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geogame.wsgi.application'

# Realtime (realtime-and-notifications): Channels ASGI application. The
# WSGI entrypoint keeps working for deployments that do not enable
# real-time; websockets are only served when the app runs under ASGI.
ASGI_APPLICATION = 'geogame.asgi.application'

# Channel layer: Redis-backed only when REDIS_URL is set (production,
# cross-process fan-out); otherwise the in-memory layer, which is
# correct for tests and single-process development and needs no extra
# services.
_REDIS_URL = os.environ.get('REDIS_URL')
if _REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_REDIS_URL]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Coalesce `scoreboard.updated` broadcasts to at most one per this many
# seconds per Session (0 disables throttling — used by tests).
REALTIME_SCOREBOARD_THROTTLE_SECONDS = float(
    os.environ.get('REALTIME_SCOREBOARD_THROTTLE_SECONDS', '2.0'),
)

# Web Push (VAPID) / FCM credentials. Without keys the push sender
# degrades to a logging stub — nothing is actually delivered, and no
# external service is contacted (see organize/push.py).
WEBPUSH_VAPID_PUBLIC_KEY = os.environ.get('WEBPUSH_VAPID_PUBLIC_KEY', '')
WEBPUSH_VAPID_PRIVATE_KEY = os.environ.get('WEBPUSH_VAPID_PRIVATE_KEY', '')
WEBPUSH_VAPID_CLAIMS_EMAIL = os.environ.get(
    'WEBPUSH_VAPID_CLAIMS_EMAIL', 'noreply@cercetador.albascout.ro',
)
FCM_SERVER_KEY = os.environ.get('FCM_SERVER_KEY', '')
# Path to a Firebase service-account JSON file (HTTP v1 credentials for
# FcmPushSender, organize/push.py). Falls back to GOOGLE_APPLICATION_CREDENTIALS
# (the firebase-admin SDK default) when unset.
FCM_CREDENTIALS_FILE = os.environ.get('FCM_CREDENTIALS_FILE', '')

# CORS (mobile-app): the Capacitor native shell serves the player app from
# a fixed WebView origin per platform (Android: https://localhost, iOS:
# capacitor://localhost) rather than the site's own origin, so those
# origins need an explicit CORS allow-list. `http://localhost` covers the
# `cap run` / live-reload dev loop. CORS_EXTRA_ORIGINS adds any further
# origins (comma-separated) without touching this file. Auth is a header
# token (not cookies), so credentialed CORS is unnecessary.
CORS_EXTRA_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_EXTRA_ORIGINS', '').split(',')
    if origin.strip()
]
CORS_ALLOWED_ORIGINS = [
    'https://localhost',
    'capacitor://localhost',
    'http://localhost',
] + CORS_EXTRA_ORIGINS
CORS_ALLOW_CREDENTIALS = False

# Mobile app-link verification (mobile-app, deployment): backs the
# /.well-known/assetlinks.json (Android App Links) and
# /.well-known/apple-app-site-association (iOS Universal Links) documents
# served by geogame/app_links.py. Safe defaults (empty fingerprints / app
# id) let the endpoints exist before signing keys and an Apple Team ID are
# available.
MOBILE_ANDROID_PACKAGE = os.environ.get(
    'MOBILE_ANDROID_PACKAGE', 'ro.yetilabs.geogame',
)
MOBILE_ANDROID_SHA256_FINGERPRINTS = [
    fingerprint.strip()
    for fingerprint in os.environ.get(
        'MOBILE_ANDROID_SHA256_FINGERPRINTS', '',
    ).split(',')
    if fingerprint.strip()
]
# Format: '<Apple Team ID>.ro.yetilabs.geogame'.
MOBILE_APPLE_APP_ID = os.environ.get('MOBILE_APPLE_APP_ID', '')
MOBILE_APP_LINKS = {
    'android_package': MOBILE_ANDROID_PACKAGE,
    'android_sha256_fingerprints': MOBILE_ANDROID_SHA256_FINGERPRINTS,
    'apple_app_id': MOBILE_APPLE_APP_ID,
    'paths': ['/nfc/*', '/join/*', '/invite/*'],
}


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DB_NAME', 'geogame'),
        'USER': os.environ.get('DB_USER', 'yeti_db'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'sql123.'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'TEST': {
            'NAME': os.environ.get('DB_TEST_NAME', 'geogame_test'),
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permiss1ions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@cercetador.albascout.ro')

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (46.068374, 23.571797),
    'DEFAULT_ZOOM': 15,
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
BASE_URL = os.environ.get("BASE_URL", "http://127.0.0.1:8200")

MEDIA_ROOT = BASE_DIR / 'media'

try:
    from .local_settings import *
except ImportError:
    pass
