# Generated by Django 6.0.4 on 2026-07-21 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organize', '0026_merge_20260721_1415'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=120)),
                ('llm_model', models.CharField(blank=True, default='', max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoring_sessions', to=settings.AUTH_USER_MODEL)),
                ('target_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoring_sessions', to='organize.game')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthoringProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — the LLM is still staging operations'), ('PENDING', 'Pending — submitted for human approval'), ('APPROVED', 'Approved — awaiting apply'), ('APPLIED', 'Applied — all approved operations written'), ('PARTIALLY_APPLIED', 'Partially applied — some operations failed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn by the author'), ('FAILED', 'Failed — apply rolled back')], default='DRAFT', max_length=20)),
                ('atomic', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoring_proposals', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoring_decisions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='authoring.authoringsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthoringAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TOOL_CALL', 'Tool call'), ('STATE_CHANGE', 'State change'), ('DECISION', 'Approval decision'), ('APPLY', 'Apply outcome')], max_length=16)),
                ('tool_name', models.CharField(blank=True, default='', max_length=80)),
                ('client_name', models.CharField(blank=True, default='', max_length=120)),
                ('llm_model', models.CharField(blank=True, default='', max_length=120)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoring_audit_events', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='authoring.authoringproposal')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='authoring.authoringsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='McpCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='authoringsession',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='authoring.mcpcredential'),
        ),
        migrations.CreateModel(
            name='ProposedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('COLLECTION', 'Collection'), ('TOWER', 'Tower'), ('ZONE', 'Zone'), ('CHALLENGE', 'Challenge'), ('GAME', 'Game'), ('GAME_ROLE', 'Game role'), ('CONFIG', 'Config')], max_length=16)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('LINK', 'Link'), ('UNLINK', 'Unlink')], max_length=8)),
                ('temp_ref', models.CharField(blank=True, default='', max_length=120)),
                ('target_ref', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('applied_object_type', models.CharField(blank=True, default='', max_length=32)),
                ('applied_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='authoring.authoringproposal')),
            ],
            options={
                'ordering': ['proposal_id', 'order', 'id'],
            },
        ),
    ]
