# Generated by Django 6.0.4 on 2026-09-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedoperation',
            name='entity_type',
            field=models.CharField(choices=[('COLLECTION', 'Collection'), ('TOWER', 'Tower'), ('ZONE', 'Zone'), ('CHALLENGE', 'Challenge'), ('GAME', 'Game'), ('GAME_ROLE', 'Game role'), ('SESSION', 'Session'), ('TEAM', 'Team'), ('CONFIG', 'Config')], max_length=16),
        ),
    ]
