# Generated by Django 3.1.6 on 2024-10-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_tower_decrease_initial_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='autocreate_zone',
            field=models.BooleanField(default=False, help_text='Creează o zonă nou, circulară, pentru acest turn', verbose_name='Creează zonă'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='decrease_initial_bonus',
            field=models.BooleanField(default=False, help_text='Dacă la fiecare recucerire ulterioară de către aceeași echipă să se înjumătățească numărul inițial de puncte obținute (minimul va fi 1)'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geogame.zone'),
        ),
    ]
