# Generated by Django 5.1.1 on 2024-10-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20241004_2355'),
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamzoneownership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.team'),
        ),
        migrations.AlterField(
            model_name='teamtowerchallenge',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.team'),
        ),
        migrations.AlterField(
            model_name='teamtowerownership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.team'),
        ),
        migrations.AddField(
            model_name='tower',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organize.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tower',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='if the game requires any tower order, use this to order towers', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organize.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamtowerchallenge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamtowerownership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamzoneownership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
