# Generated by Django 6.0.4 on 2026-04-19 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_teamtowerchallenge_submitted_by'),
        ('organize', '0004_game_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='organize.game'),
        ),
    ]
