# Generated by Django 6.0.4 on 2026-07-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_backfill_challenge_game'),
        ('organize', '0010_game_fail_cooloff_scaling_game_fail_counter_reset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('restore_on_resume', models.BooleanField(default=True)),
                ('tower_ownerships', models.JSONField(blank=True, default=list)),
                ('zone_ownerships', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_windows', to='organize.session')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamTowerFailCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive_fails', models.PositiveIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organize.team')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tower')),
            ],
            options={
                'unique_together': {('team', 'tower')},
            },
        ),
    ]
