# Generated by Django 6.0.4 on 2026-07-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_pausewindow_teamtowerfailcounter'),
        ('organize', '0011_gamerole_teamrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='require_holders_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='required_roles',
            field=models.ManyToManyField(blank=True, related_name='required_by_challenges', to='organize.gamerole'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='role_requirement_mode',
            field=models.CharField(choices=[('NONE', 'No role requirement'), ('ALL', 'One holder for each required role'), ('ANY', 'At least one required role held')], default='NONE', max_length=8),
        ),
    ]
