# Generated by Django 6.0.4 on 2026-07-21 00:20

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_challenge_role_requirements'),
        ('organize', '0017_dementors_ble_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='DementorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('WIZARD', 'Wizard'), ('DEMENTOR', 'Dementor')], default='WIZARD', max_length=16)),
                ('energy', models.FloatField(default=0.0)),
                ('alive', models.BooleanField(default=True)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('last_delta', models.FloatField(default=0.0)),
                ('hold_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dementor_states', to='organize.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dementor_states', to='organize.session')),
            ],
        ),
        migrations.CreateModel(
            name='DementorFlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(choices=[('WIZARD', 'Wizard'), ('DEMENTOR', 'Dementor')], max_length=16)),
                ('to_role', models.CharField(choices=[('WIZARD', 'Wizard'), ('DEMENTOR', 'Dementor')], max_length=16)),
                ('cause', models.CharField(choices=[('DRAINED', 'Wizard drained to empty — flipped to dementor'), ('DIED', 'Wizard drained to empty — out of play'), ('REVERSE_GAME', 'Held by a wizard group — flipped to wizard'), ('CONVERSION', 'Energy crossed the conversion threshold')], max_length=16)),
                ('happened_at', models.DateTimeField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flips', to='game.dementorstate')),
            ],
            options={
                'ordering': ['-happened_at'],
            },
        ),
        migrations.CreateModel(
            name='ProximityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_bucket', models.CharField(max_length=16)),
                ('confidence', models.FloatField(default=0.5)),
                ('corroborated', models.BooleanField(default=False)),
                ('derived_at', models.DateTimeField()),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organize.userprofile')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organize.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_events', to='organize.session')),
            ],
            options={
                'ordering': ['-derived_at'],
            },
        ),
        migrations.CreateModel(
            name='ProximityIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=game.models._generate_proximity_token, max_length=16, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('rotates_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_identities', to='organize.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_identities', to='organize.session')),
            ],
        ),
        migrations.CreateModel(
            name='ProximityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.JSONField(blank=True, default=list)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_reports', to='organize.userprofile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='game.proximityidentity')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_reports', to='organize.session')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dementorstate',
            constraint=models.UniqueConstraint(fields=('session', 'player'), name='unique_dementor_state'),
        ),
        migrations.AddIndex(
            model_name='proximityevent',
            index=models.Index(fields=['session', 'derived_at'], name='game_proxim_session_91308b_idx'),
        ),
        migrations.AddConstraint(
            model_name='proximityidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('session', 'player'), name='unique_active_proximity_identity'),
        ),
        migrations.AddIndex(
            model_name='proximityreport',
            index=models.Index(fields=['session', 'received_at'], name='game_proxim_session_4bdcb2_idx'),
        ),
    ]
