# Generated by Django 6.0.4 on 2026-07-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_backfill_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='game',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='game',
        ),
    ]
