# Generated by Django 6.0.4 on 2026-07-21 05:50

import django.db.models.deletion
import game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_ble_proximity_dementors'),
        ('organize', '0017_dementors_ble_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(default=game.models._generate_badge_id, max_length=16, unique=True)),
                ('hardware_mac', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=32)),
                ('battery_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('MAINTENANCE', 'Maintenance / charging'), ('LOST', 'Lost / not returned'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['badge_id'],
            },
        ),
        migrations.CreateModel(
            name='GatewayNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transport', models.CharField(choices=[('WIFI', 'ESP32 + WiFi'), ('CELLULAR', 'ESP32 + 4G/cellular'), ('TABLET', 'Organizer tablet relay app')], default='WIFI', max_length=16)),
                ('token', models.CharField(default=game.models._generate_gateway_token, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('coverage_note', models.TextField(blank=True, default='')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='proximityevent',
            name='source',
            field=models.CharField(choices=[('PHONE', 'Phone BLE'), ('BADGE', 'Wearable badge (ESP-NOW via gateway)'), ('MIXED', 'Corroborated across phone and badge')], default='PHONE', max_length=8),
        ),
        migrations.AddField(
            model_name='proximityreport',
            name='source',
            field=models.CharField(choices=[('PHONE', 'Phone BLE'), ('BADGE', 'Wearable badge (ESP-NOW via gateway)'), ('MIXED', 'Corroborated across phone and badge')], default='PHONE', max_length=8),
        ),
        migrations.CreateModel(
            name='BadgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_assignments', to='organize.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_assignments', to='organize.session')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_assignments', to='organize.team')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='game.badgedevice')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('badge',), name='unique_active_badge_assignment')],
            },
        ),
        migrations.CreateModel(
            name='BadgeObservationSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_markers', to='game.badgedevice')),
                ('seen_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.badgedevice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('badge', 'seen_badge', 'counter'), name='unique_badge_observation_counter')],
            },
        ),
        migrations.CreateModel(
            name='BadgeTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activity', models.CharField(blank=True, choices=[('RUNNING', 'Running'), ('STANDING', 'Standing'), ('STILL', 'Still')], max_length=16, null=True)),
                ('gesture', models.CharField(blank=True, choices=[('CAST', 'Cast flick'), ('DRAIN', 'Drain flick')], max_length=16, null=True)),
                ('imu', models.JSONField(blank=True, default=dict)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='game.badgedevice')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_telemetry', to='organize.session')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['badge', 'recorded_at'], name='game_badget_badge_i_fd1be8_idx')],
            },
        ),
    ]
