# Generated by Django 6.0.4 on 2026-07-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_challenge_role_requirements'),
        ('game', '0024_remove_tower_zone_game_fk'),
    ]

    operations = [
    ]
