# Generated by Django 6.0.4 on 2026-07-21 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_merge_20260721_0017'),
        ('organize', '0017_merge_20260721_0017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('TOWER', 'One tower'), ('ZONE', 'One zone'), ('GLOBAL', 'Whole game')], default='GLOBAL', max_length=8)),
                ('multiplier_type', models.CharField(choices=[('MANUAL', 'Manual — admin toggles is_active live'), ('SCHEDULED', 'Scheduled — Session-relative offset window'), ('RANDOM_BONUS', 'Random bonus — dropped live with an absolute window')], default='MANUAL', max_length=16)),
                ('factor', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('window_start_offset', models.DurationField(blank=True, null=True)),
                ('window_end_offset', models.DurationField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_multipliers_created', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_multipliers', to='organize.game')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_multipliers', to='organize.session')),
                ('tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_multipliers', to='game.tower')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_multipliers', to='game.zone')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
