# Generated by Django 6.0.4 on 2026-07-21 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_merge_20260721_0017'),
        ('organize', '0018_tower_lock_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, choices=[('FINISHED', 'Finished — a confirmed finish captured the tower'), ('EXPIRED', 'Expired — the finish deadline passed without a confirmed finish'), ('CANCELLED', 'Cancelled — voluntarily or by staff, before finishing')], max_length=16, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_locks', to='organize.teamgroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_locks', to='organize.team')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='game.tower')),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('tower', 'group'), name='unique_active_tower_lock_per_group')],
            },
        ),
    ]
