# Generated by Django 6.0.4 on 2026-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_merge_20260721_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='proximity_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='conquest_rule',
            field=models.CharField(blank=True, choices=[('ALL', 'All towers — a team must hold every active member tower'), ('MAJORITY', 'Majority of towers (default, historical behavior)'), ('ANY', 'Any tower — most towers wins, ties broken by most recent capture')], max_length=16, null=True),
        ),
    ]
