# Generated by Django 6.0.4 on 2026-07-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_merge_20260721_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='review_mode',
            field=models.CharField(blank=True, choices=[('AUTO', 'Auto (validated by the system)'), ('MANUAL', 'Manual (validated by staff)')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text question (staff-reviewed)'), ('PHOTO', 'Photo evidence (staff-reviewed)'), ('NFC_QR', 'NFC/QR venue code (auto-validated)'), ('RFID', 'RFID tag scan (auto-validated)')], default='TEXT', max_length=8),
        ),
        migrations.AddField(
            model_name='challenge',
            name='type_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='challenge',
            name='validation_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='teamtowerchallenge',
            name='submitted_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
