# Generated by Django 6.0.4 on 2026-07-21 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_merge_20260721_0017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='authored_accuracy_m',
            field=models.FloatField(blank=True, help_text='GPS accuracy in metres of the field capture that placed this tower (provenance).', null=True),
        ),
        migrations.CreateModel(
            name='TowerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tower_photos')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tower_photos', to=settings.AUTH_USER_MODEL)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='game.tower')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
