# Generated by Django 6.0.4 on 2026-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_zone_conquest_rule_tower_proximity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='towers', to='game.zone'),
        ),
    ]
