# Generated by Django 6.0.4 on 2026-07-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_location_ping_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_members_present', models.PositiveIntegerField(default=1)),
                ('method', models.CharField(choices=[('GEOFENCE', 'Geofence (live-location pings)'), ('PHOTO', 'Photo of the required people (staff-reviewed)'), ('GEOFENCE_OR_PHOTO', 'Geofence, with photo fallback')], default='GEOFENCE', max_length=32)),
                ('geofence_radius_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('window_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresenceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_count', models.PositiveIntegerField()),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(choices=[('GEOFENCE', 'Geofence (live-location pings)'), ('PHOTO', 'Photo of the required people (staff-reviewed)'), ('GEOFENCE_OR_PHOTO', 'Geofence, with photo fallback')], max_length=32)),
                ('verified_member_ids', models.JSONField(blank=True, default=list)),
                ('window_seconds', models.PositiveIntegerField(default=0)),
                ('window_satisfied', models.BooleanField(blank=True, null=True)),
                ('satisfied', models.BooleanField(default=False)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_tower_challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence_check', to='game.teamtowerchallenge')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='presence_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='game.presencerequirement'),
        ),
    ]
