# Generated by Django 6.0.4 on 2026-07-21 07:01

import django.db.models.deletion
import game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_stamp_existing_challenges_text'),
        ('organize', '0018_nfc_config_knobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NfcTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=game.models._generate_nfc_token, editable=False, max_length=64, unique=True)),
                ('mode', models.CharField(choices=[('LEGACY_URL', 'Legacy forwardable URL (mirrors /tower/rfid/<code>/)'), ('SECURE_TOKEN', 'Secure app-only token')], default='SECURE_TOKEN', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('hidden_hint', models.TextField(blank=True, default='')),
                ('expected_counter', models.PositiveIntegerField(blank=True, null=True)),
                ('last_counter', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='game.challenge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tags_created', to=settings.AUTH_USER_MODEL)),
                ('tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_tags', to='game.tower')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('CONFIRMED', 'Confirmed capture'), ('PENDING', 'Pending (held / manual review)'), ('REJECTED_NO_TEAM', 'Rejected: no active team'), ('REJECTED_INACTIVE', 'Rejected: tag inactive'), ('REJECTED_DISABLED', 'Rejected: secure mode disabled'), ('REJECTED_APP', 'Rejected: app-origin marker missing'), ('REJECTED_SCOPE', 'Rejected: target outside session scope'), ('REJECTED_REPLAY', 'Rejected: replay counter'), ('REJECTED_PROXIMITY', 'Rejected: out of proximity'), ('REJECTED_STATE', 'Rejected: paused / locked out'), ('REJECTED_CODE', 'Rejected: challenge code validation')], max_length=32)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('counter', models.PositiveIntegerField(blank=True, null=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_scans', to='organize.teammembership')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_scans', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_scans', to='organize.session')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='game.nfctag')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
