# Generated by Django 6.0.4 on 2026-07-21 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_stamp_existing_challenges_text'),
        ('organize', '0018_game_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(choices=[('FIXED_ORDER', 'Fixed order — linear 1→2→3→4'), ('GRAPH', 'Graph — branching, the party chooses'), ('CIRCUIT', 'Circuit — shared loop, per-party start offset')], default='FIXED_ORDER', max_length=16)),
                ('starting_knowledge', models.CharField(choices=[('ALL_KNOWN', 'All points known from the start'), ('ONE_KNOWN', 'Only the start point known'), ('NONE_KNOWN', 'Nothing known — discover the start')], default='ONE_KNOWN', max_length=16)),
                ('participation', models.CharField(choices=[('TEAM', 'Teams'), ('SOLO', 'Solo players')], default='TEAM', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trail', to='organize.game')),
            ],
        ),
        migrations.CreateModel(
            name='TrailStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_start', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('clue_text', models.TextField(blank=True, default='')),
                ('start_hint', models.TextField(blank=True, default='')),
                ('gate_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates_trail_steps', to='game.challenge')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_steps', to='game.tower')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='game.trail')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamTrailRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_routes', to='organize.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_routes', to='organize.session')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_routes', to='organize.team')),
                ('start_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_starting_here', to='game.trailstep')),
            ],
        ),
        migrations.CreateModel(
            name='TeamTrailProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('REVEALED', 'Revealed'), ('ARRIVED', 'Arrived'), ('UNLOCKED', 'Unlocked')], default='REVEALED', max_length=8)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_progress', to='organize.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_progress', to='organize.session')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trail_progress', to='organize.team')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='game.trailstep')),
            ],
        ),
        migrations.CreateModel(
            name='TrailEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.TextField(blank=True, default='')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='game.trail')),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='game.trailstep')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='game.trailstep')),
            ],
            options={
                'unique_together': {('from_step', 'to_step')},
            },
        ),
        migrations.CreateModel(
            name='TeamTrailRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps', to='game.teamtrailroute')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.trailstep')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('route', 'position'), ('route', 'step')},
            },
        ),
        migrations.AddConstraint(
            model_name='teamtrailroute',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('session', 'team'), name='unique_trail_route_per_team'),
        ),
        migrations.AddConstraint(
            model_name='teamtrailroute',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('session', 'player'), name='unique_trail_route_per_player'),
        ),
        migrations.AddConstraint(
            model_name='teamtrailprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('session', 'team', 'step'), name='unique_trail_progress_per_team_step'),
        ),
        migrations.AddConstraint(
            model_name='teamtrailprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('session', 'player', 'step'), name='unique_trail_progress_per_player_step'),
        ),
    ]
