# Generated by Django 6.0.4 on 2026-07-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_copy_tower_zone_to_zones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='zone',
        ),
    ]
