# Generated by Django 6.0.4 on 2026-07-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_presence_requirement_check'),
        ('game', '0029_remove_tower_zone_fk'),
    ]

    operations = [
    ]
