# Generated by Django 6.0.4 on 2026-07-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_field_authoring'),
        ('game', '0030_merge_20260721_0655'),
    ]

    operations = [
    ]
