# Generated by Django 6.0.4 on 2026-07-21 07:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_merge_20260721_0655'),
        ('organize', '0021_tower_visibility_discovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='challenge_visibility',
            field=models.CharField(blank=True, choices=[('HIDDEN_UNTIL_ARRIVAL', 'Hidden until arrival — legible only inside the activation area'), ('VISIBLE_ANYWHERE', 'Visible anywhere — legible from afar (default, historical behavior)')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='discoverability',
            field=models.CharField(blank=True, choices=[('HIDDEN', 'Hidden — pops up when a team walks within proximity'), ('VISIBLE', 'Visible — always on the map (default, historical behavior)'), ('FOG_REVEAL', 'Fog reveal — revealed by entering or covering the zone')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='fog_reveal_coverage_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TeamZoneCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('coverage_pct', models.FloatField(default=0)),
                ('revealed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_coverages', to='organize.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_coverages', to='organize.team')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_coverages', to='game.zone')),
            ],
            options={
                'unique_together': {('session', 'team', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='TowerDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('PROXIMITY', 'Walked within the tower proximity'), ('ZONE_ENTRY', 'Entered the tower zone'), ('ZONE_COVERAGE', 'Covered enough of the tower zone'), ('ALWAYS_VISIBLE', 'Always visible'), ('STAFF', 'Revealed by staff')], max_length=16)),
                ('discovered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tower_discoveries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_discoveries', to='organize.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_discoveries', to='organize.team')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='game.tower')),
            ],
            options={
                'ordering': ['-discovered_at'],
                'unique_together': {('session', 'team', 'tower')},
            },
        ),
    ]
