# Generated by Django 6.0.4 on 2026-07-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_stamp_existing_challenges_text'),
        ('game', '0031_merge_0026_field_authoring_0030_merge_20260721_0655'),
    ]

    operations = [
    ]
