# Generated by Django 6.0.4 on 2026-07-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_nfc_tag_and_tag_scan'),
        ('game', '0032_merge_20260721_1049'),
    ]

    operations = [
    ]
