# Generated by Django 6.0.4 on 2026-07-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_trail_discovery'),
        ('game', '0033_merge_20260721_1109'),
    ]

    operations = [
    ]
