# Generated by Django 6.0.4 on 2026-07-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_towerlock'),
        ('game', '0034_merge_0028_trail_discovery_0033_merge_20260721_1109'),
    ]

    operations = [
    ]
