# Generated by Django 6.0.4 on 2026-07-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_score_multiplier'),
        ('game', '0035_merge_20260721_1201'),
    ]

    operations = [
    ]
