# Generated by Django 6.0.4 on 2026-07-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_ble_proximity_dementors'),
        ('game', '0036_merge_0026_score_multiplier_0035_merge_20260721_1201'),
    ]

    operations = [
    ]
