# Generated by Django 6.0.4 on 2026-07-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_wearable_badge_hardware'),
        ('game', '0037_merge_20260721_1317'),
    ]

    operations = [
    ]
