# Generated by Django 6.0.4 on 2026-07-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_tower_visibility_discovery'),
        ('game', '0038_merge_20260721_1337'),
    ]

    operations = [
    ]
