# Generated by Django 6.0.4 on 2026-09-23 22:49

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_sessionoverviewlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('icon', models.CharField(default='bi-geo-alt-fill', help_text='Bootstrap Icons class name, e.g. bi-droplet-fill.', max_length=64)),
                ('color', colorfield.fields.ColorField(default='#5F6B7A', image_field=None, max_length=18, samples=None)),
                ('proximity_meters', models.PositiveIntegerField(blank=True, help_text='Default capture radius for this kind of place. Blank falls through to the Game default.', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tower',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='tower',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tower',
            name='tower_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='towers', to='game.towertype'),
        ),
    ]
